name: Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 10.x
    - run: npm ci
    - run: npm run build
      env:
        NODE_ENV: production
        ENABLE_SERVICE_WORKER: 1
    - run: npm test
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: dist
        single-commit: true
        git-config-name: "packager build bot"
        git-config-email: "packagerbuildbot@turbowarp.org"